[package]
name = "hex_convert"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
getch = "0.3.1"
pancurses = "0.17"
rand = "*"
device_query = "*"
winapi = { version = "0.3", features = ["winuser"] }